### ISSUE TITLE
faced this issue while training 

### ISSUE THREAD

**Issue by mayur17mirashi** [MicrocontrollersAndMore/TensorFlow_Tut_2_Classification_Walk-through#1]
Traceback (most recent call last):
  File "retrain.py", line 1221, in <module>
    main()
  File "retrain.py", line 210, in main
    resized_image_tensor, bottleneck_tensor, ARCHITECTURE)
  File "retrain.py", line 808, in cache_bottlenecks
    jpeg_data_tensor, decoded_image_tensor, resized_input_tensor, bottleneck_tensor, architecture)
  File "retrain.py", line 848, in get_or_create_bottleneck
    decoded_image_tensor, resized_input_tensor, bottleneck_tensor)
  File "retrain.py", line 922, in create_bottleneck_file
    with open(bottleneck_path, 'w') as bottleneck_file:
FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\hp\\Desktop\\TensorFlow_Tut_2_Classification_Walk-through-master\\TensorFlow_Tut_2_Classification_Walk-through-master/bottleneck_data\\macncheese\\Homemade-One-Pot-Stovetop-Macaroni-and-Cheese-Cooked-in-Milk-by-Five-Heart-Home_700pxTitle1.jpg_inception_v3.txt'

**Comment by prasanth-rgb** [comment]
#1. When i used one similar code from github, i had to handle the exceptions when it meet error with JPEG decoding (invalid jpeg files) for bottleneck creation. 
#2. For some files, bottleneck files have only NULL and loading this file followed by string.split and float conversion shall cause exception. Handled those as well.

I am not sure whether the mentioned issue belongs to that
